server:
  port: 9001

spring:
  application:
    name: battcn-hello-service
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      discovery:
        enabled: true
        prefer-ip-address: true
